### ISSUE TITLE
后端无法启动

### ISSUE THREAD

**Issue by tangsiqiVicky** [Damao2250/WebScoketChat#2]
后端启动报错
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/tangsiqi/Downloads/WebScoketChat-master/back-end/index.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
tangsiqideMacBook-Pro:back-end tangsiqi$ node

**Comment by Damao2250** [comment]
目前还有些问题，稍等，过两天修复这个bug

**Comment by Damao2250** [comment]
已更新
